name: CustomItemsPAPER
version: 1.3.4
main: me.jsinco.customitemspaper.CustomItemsPAPER
api-version: 1.19
author: Jsinco
commands:
  test:
  cely:
    description: Colored elytras
    usage: /<command> <item>
    permission: customitemspaper.giveitem
    aliases:
      - coloredelytra
  giveitem:
    description: Give a custom item to a player
    usage: /<command> <item>
    permission: customitemspaper.giveitem
    aliases:
      - getitem
      - get